apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - image: nikolabo/echo-frontend-grpc
        name: frontend-grpc
        volumeMounts:
        - mountPath: /interceptors
          name: interceptor
      volumes:
      - name: interceptor
        persistentVolumeClaim:
          claimName: frontend-interceptor-pvc
  selector:
    matchLabels:
      app: frontend
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-interceptor-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/interceptors
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-interceptor-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  clusterIP: 10.96.77.76
  ports:
  - name: server
    port: 9000
    targetPort: 9000
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
      - image: nikolabo/echo-server-grpc
        name: server-grpc
        volumeMounts:
        - mountPath: /interceptors
          name: interceptor
      volumes:
      - name: interceptor
        persistentVolumeClaim:
          claimName: server-interceptor-pvc 
  selector:
    matchLabels:
      app: server
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: server-interceptor-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/interceptors
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-interceptor-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---