apiVersion: v1
kind: Service
metadata:
  labels:
    app: details
  name: details
spec:
  ports:
  - name: grpc
    port: 8081
  selector:
    app: details
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    account: details
  name: bookinfo-details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: details
    version: v1
  name: details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v1
  template:
    metadata:
      labels:
        app: details
        version: v1
    spec:
      containers:
      - args:
        - details
        command:
        - /go/bin/cmd
        image: xzhu0027/bookinfo_grpc_details:latest
        imagePullPolicy: Always
        name: details
        ports:
        - containerPort: 8081
      nodeName: h4.hotelbench.meshbench-pg0.clemson.cloudlab.us
      serviceAccountName: bookinfo-details
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: details-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/volumes/details-pv
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - h4.hotelbench.meshbench-pg0.clemson.cloudlab.us
  storageClassName: details-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: details-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: details-storage
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-details
  name: mongodb-details
spec:
  ports:
  - name: mongodb-details
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb-details
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-details
  name: mongodb-details
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb-details
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongodb-details
    spec:
      containers:
      - image: mongo:4.4.6
        name: bookinfo-details-mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /data/db
          name: details
      nodeName: h4.hotelbench.meshbench-pg0.clemson.cloudlab.us
      restartPolicy: Always
      volumes:
      - name: details
        persistentVolumeClaim:
          claimName: details-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: productpage
  name: productpage
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: http
    port: 8080
  selector:
    app: productpage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    account: productpage
  name: bookinfo-productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: productpage
    version: v1
  name: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - args:
        - productpage
        command:
        - /go/bin/cmd
        image: xzhu0027/bookinfo_grpc_productpage
        imagePullPolicy: Always
        name: productpage
        ports:
        - containerPort: 8080
      nodeName: h2.hotelbench.meshbench-pg0.clemson.cloudlab.us
      serviceAccountName: bookinfo-productpage
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-ratings
  name: mongodb-ratings
spec:
  ports:
  - name: mongodb-ratings
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb-ratings
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-ratings
  name: mongodb-ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb-ratings
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongodb-ratings
    spec:
      containers:
      - image: mongo:4.4.6
        name: bookinfo-ratings-mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /data/db
          name: ratings
      nodeName: h5.hotelbench.meshbench-pg0.clemson.cloudlab.us
      restartPolicy: Always
      volumes:
      - name: ratings
        persistentVolumeClaim:
          claimName: ratings-pvc
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings
  name: ratings
spec:
  ports:
  - name: ratings
    port: 8082
  selector:
    app: ratings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    account: ratings
  name: bookinfo-ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ratings
    version: v1
  name: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      containers:
      - args:
        - ratings
        command:
        - /go/bin/cmd
        image: xzhu0027/bookinfo_grpc_ratings:latest
        name: ratings
        ports:
        - containerPort: 8082
      nodeName: h5.hotelbench.meshbench-pg0.clemson.cloudlab.us
      serviceAccountName: bookinfo-ratings
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ratings-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/volumes/ratings-pv
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - h5.hotelbench.meshbench-pg0.clemson.cloudlab.us
  storageClassName: ratings-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ratings-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ratings-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reviews
  name: reviews
spec:
  ports:
  - name: reviews
    port: 8083
  selector:
    app: reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    account: reviews
  name: bookinfo-reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reviews
    version: v3
  name: reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
      - args:
        - reviews
        command:
        - /go/bin/cmd
        env:
        - name: REVIEWS_VERSION
          value: v3
        image: xzhu0027/bookinfo_grpc_reviews:latest
        name: reviews
        ports:
        - containerPort: 8083
      nodeName: h3.hotelbench.meshbench-pg0.clemson.cloudlab.us
      serviceAccountName: bookinfo-reviews
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-reviews
  name: mongodb-reviews
spec:
  ports:
  - name: mongodb-reviews
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb-reviews
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongodb-reviews
  name: mongodb-reviews
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb-reviews
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongodb-reviews
    spec:
      containers:
      - image: mongo:4.4.6
        name: bookinfo-reviews-mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - mountPath: /data/db
          name: reviews
      nodeName: h3.hotelbench.meshbench-pg0.clemson.cloudlab.us
      restartPolicy: Always
      volumes:
      - name: reviews
        persistentVolumeClaim:
          claimName: reviews-pvc
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: reviews-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/volumes/reviews-pv
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - h3.hotelbench.meshbench-pg0.clemson.cloudlab.us
  storageClassName: reviews-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reviews-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: reviews-storage
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: jaeger
  name: jaeger
spec:
  ports:
  - name: '14269'
    port: 14269
    targetPort: 14269
  - name: '5778'
    port: 5778
    targetPort: 5778
  - name: '14268'
    port: 14268
    targetPort: 14268
  - name: '14267'
    port: 14267
    targetPort: 14267
  - name: '16686'
    port: 16686
    targetPort: 16686
  - name: '5775'
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: '6831'
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: '6832'
    port: 6832
    protocol: UDP
    targetPort: 6832
  selector:
    service: jaeger
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jaeger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: jaeger
    spec:
      containers:
      - image: jaegertracing/all-in-one:latest
        name: bookinfo-jaeger
        ports:
        - containerPort: 14269
        - containerPort: 5778
        - containerPort: 14268
        - containerPort: 14267
        - containerPort: 16686
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
      nodeName: h2.hotelbench.meshbench-pg0.clemson.cloudlab.us
      restartPolicy: Always
status: {}
